# Generated by Django 6.0.7 on 2026-08-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
    ]
