# Generated by Django 6.0.6 on 2026-06-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employees')),
            ],
            options={
                'db_table': 'employee_profile',
            },
        ),
    ]
