# Generated by Django 6.0.6 on 2026-06-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_projects_alter_department_table_newemployee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newemployee',
            table='new_employees',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
    ]
