# Generated by Django 6.0.3 on 2026-06-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newemployee_table_alter_projects_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='welcome_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.welcome'),
        ),
    ]
